// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using currencyApi.Data;

namespace currency_api.Migrations
{
    [DbContext(typeof(CurrenciesContext))]
    [Migration("20200329121846_SeedUserRolesData")]
    partial class SeedUserRolesData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("currencyApi.Models.Currency", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nchar(3)")
                        .IsFixedLength(true)
                        .HasMaxLength(3);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Code = "EUR",
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(2506),
                            Description = "Euro",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 2L,
                            Code = "USD",
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(2553),
                            Description = "US Dollar",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 3L,
                            Code = "CHF",
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(2555),
                            Description = "Swiss Franc",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 4L,
                            Code = "GBP",
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(2556),
                            Description = "British Pound",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 5L,
                            Code = "JPY",
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(2558),
                            Description = "Japan Yen",
                            IsActive = true,
                            IsDeleted = false
                        },
                        new
                        {
                            Id = 6L,
                            Code = "CAD",
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(2560),
                            Description = "Canadian Dollar",
                            IsActive = true,
                            IsDeleted = false
                        });
                });

            modelBuilder.Entity("currencyApi.Models.CurrencyRate", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long>("BaseCurrencyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18, 10)");

                    b.Property<long>("TargetCurrencyId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TargetCurrencyId");

                    b.HasIndex("BaseCurrencyId", "TargetCurrencyId")
                        .IsUnique();

                    b.ToTable("CurrencyRates");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            BaseCurrencyId = 1L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(4090),
                            IsActive = true,
                            IsDeleted = false,
                            Rate = 1.3764m,
                            TargetCurrencyId = 2L
                        },
                        new
                        {
                            Id = 2L,
                            BaseCurrencyId = 1L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(4159),
                            IsActive = true,
                            IsDeleted = false,
                            Rate = 1.2079m,
                            TargetCurrencyId = 3L
                        },
                        new
                        {
                            Id = 3L,
                            BaseCurrencyId = 1L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(4163),
                            IsActive = true,
                            IsDeleted = false,
                            Rate = 0.8731m,
                            TargetCurrencyId = 4L
                        },
                        new
                        {
                            Id = 4L,
                            BaseCurrencyId = 2L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(4165),
                            IsActive = true,
                            IsDeleted = false,
                            Rate = 76.7200m,
                            TargetCurrencyId = 5L
                        },
                        new
                        {
                            Id = 5L,
                            BaseCurrencyId = 3L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(4167),
                            IsActive = true,
                            IsDeleted = false,
                            Rate = 1.1379m,
                            TargetCurrencyId = 2L
                        },
                        new
                        {
                            Id = 6L,
                            BaseCurrencyId = 4L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(4169),
                            IsActive = true,
                            IsDeleted = false,
                            Rate = 1.5648m,
                            TargetCurrencyId = 6L
                        });
                });

            modelBuilder.Entity("currencyApi.Models.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 762, DateTimeKind.Utc).AddTicks(4481),
                            Email = "user@currencies.cur",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "xxx",
                            UserName = "admin"
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 762, DateTimeKind.Utc).AddTicks(5859),
                            Email = "user@currencies.cur",
                            IsActive = true,
                            IsDeleted = false,
                            PasswordHash = "xxx",
                            UserName = "user"
                        });
                });

            modelBuilder.Entity("currencyApi.Models.UserRole", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "USER_CURRENCIES_RATES"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "ADMIN_CURRENCIES"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "ADMIN_RATES"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "ADMIN_USERS"
                        });
                });

            modelBuilder.Entity("currencyApi.Models.UserRoleRelation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<long>("RoleId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedByUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRoleRelations");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(1287),
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = 1L,
                            UserId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(1335),
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = 1L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 3L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(1337),
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = 2L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 4L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(1339),
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = 3L,
                            UserId = 2L
                        },
                        new
                        {
                            Id = 5L,
                            CreatedAt = new DateTime(2020, 3, 29, 12, 18, 45, 764, DateTimeKind.Utc).AddTicks(1340),
                            IsActive = true,
                            IsDeleted = false,
                            RoleId = 4L,
                            UserId = 2L
                        });
                });

            modelBuilder.Entity("currencyApi.Models.CurrencyRate", b =>
                {
                    b.HasOne("currencyApi.Models.Currency", "BaseCurrency")
                        .WithMany("CurrencyRates")
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("currencyApi.Models.Currency", "TargetCurrency")
                        .WithMany()
                        .HasForeignKey("TargetCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("currencyApi.Models.UserRoleRelation", b =>
                {
                    b.HasOne("currencyApi.Models.UserRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("currencyApi.Models.User", "User")
                        .WithMany("UserRoleRelations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
